version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1

jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.0
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run RSpec tests
          command: bundle exec rspec

  rubocop:
    docker:
      - image: cimg/ruby:3.0
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run RuboCop
          command: bundle exec rubocop

  rbs:
    docker:
      - image: cimg/ruby:3.0
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run RBS
          command: bundle exec srb tc

workflows:
  version: 2
  test-workflow:
    jobs:
      - rspec
      - rubocop
      - rbs
