version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0

    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - run:
          name: Run Rspec tests
          command: bundle exec rspec
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
      - run:
          name: Run rbs
          command: bundle exec srb tc

workflows:
  sample:
    jobs:
      - build