version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1
  codecov: codecov/codecov@4.0.1

executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:3.0
    working_directory: ~/repo
    environment:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle

jobs:
  test:
    executor: ruby-executor
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            - v2-dependencies-
      
      - run:
          name: Install dependencies
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
      
      - run:
          name: Run tests with coverage
          command: |
            mkdir -p /tmp/test-results
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress
      
      - run:
          name: Check test coverage
          command: |
            if [ -f "coverage/.last_run.json" ]; then
              coverage=$(ruby -rjson -e "puts JSON.parse(File.read('coverage/.last_run.json'))['result']['line']")
              echo "Test coverage: ${coverage}%"
              if (( $(echo "$coverage < 90" | bc -l) )); then
                echo "Coverage is below 90%"
                exit 1
              fi
            fi
      
      - codecov/upload:
          file: coverage/.resultset.json
      
      - store_test_results:
          path: /tmp/test-results
      
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      
      - store_artifacts:
          path: coverage
          destination: coverage

  lint:
    executor: ruby-executor
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            - v2-dependencies-
      
      - run:
          name: Install dependencies
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      
      - run:
          name: Run Rubocop
          command: bundle exec rubocop --format progress --format junit --out /tmp/rubocop-results.xml
      
      - store_test_results:
          path: /tmp
      
      - store_artifacts:
          path: /tmp/rubocop-results.xml
          destination: rubocop-results.xml

  type_check:
    executor: ruby-executor
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            - v2-dependencies-
      
      - run:
          name: Install dependencies
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      
      - run:
          name: Run Steep type checking
          command: bundle exec steep check

  security_scan:
    executor: ruby-executor
    steps:
      - checkout
      
      - run:
          name: Install bundler-audit
          command: gem install bundler-audit
      
      - run:
          name: Update vulnerability database
          command: bundle-audit update
      
      - run:
          name: Check for vulnerabilities
          command: bundle-audit check

  build:
    executor: ruby-executor
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            - v2-dependencies-
      
      - run:
          name: Install dependencies
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      
      - run:
          name: Build gem
          command: |
            gem build kansai_train_info.gemspec
            mkdir -p pkg
            mv *.gem pkg/
      
      - persist_to_workspace:
          root: .
          paths:
            - pkg/*.gem
      
      - store_artifacts:
          path: pkg
          destination: gem

workflows:
  version: 2
  
  test_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      
      - lint:
          filters:
            tags:
              only: /.*/
      
      - type_check:
          filters:
            tags:
              only: /.*/
      
      - security_scan:
          filters:
            tags:
              only: /.*/
      
      - build:
          requires:
            - test
            - lint
            - type_check
            - security_scan
          filters:
            tags:
              only: /.*/
            branches:
              only: master
  
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - security_scan
      - test
      - lint