module KansaiTrainInfo
  def self.get: (Array[String] route_array, ?url: bool) -> String?
  def self.help: () -> void

  private
  def self.http_client: () -> HttpClient
  def self.fetch_route_status: (Route route) -> String?
  def self.fetch_description: (String detail_url) -> String
end