# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Nokogiri::HTML; end
module ::RSpec; end
module ::Thor; end
