name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  RUBY_VERSION: '3.0'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Run tests
      run: bundle exec rspec
    
    - name: Upload coverage to Codecov
      if: matrix.ruby-version == '3.0'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/.resultset.json
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    
    - name: Run Rubocop
      run: bundle exec rubocop

  type-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    
    - name: Run Steep
      run: bundle exec steep check

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    
    - name: Install bundler-audit
      run: gem install bundler-audit
    
    - name: Update vulnerability database
      run: bundle-audit update
    
    - name: Run security audit
      run: bundle-audit check

  build:
    runs-on: ubuntu-latest
    needs: [test, lint, type-check, security]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    
    - name: Build gem
      run: |
        gem build kansai_train_info.gemspec
        mkdir -p pkg
        mv *.gem pkg/
    
    - name: Upload gem artifact
      uses: actions/upload-artifact@v4
      with:
        name: gem
        path: pkg/*.gem